export type Language = 'ru' | 'en' | 'zh';

export const resetPasswordTranslations = {
    ru: {
        title: 'Восстановление пароля',
        subtitle: 'Введите email, мы отправим на него код',
        email: 'Email',
        emailPlaceholder: 'Введите email',
        code: 'Код из письма',
        newPassword: 'Новый пароль',
        confirmPassword: 'Повторите новый пароль',
        sendCode: 'Отправить код',
        sending: 'Отправка…',
        verify: 'Проверить код',
        checking: 'Проверка…',
        resend: 'Отправить код повторно',
        submit: 'Сменить пароль',
        saving: 'Сохранение…',
        backToLogin: '← Вернуться ко входу',
        placeholders: {
            new: 'Минимум 8 символов',
            confirm: 'Повторите новый пароль',
        },
        errors: {
            mismatch: 'Пароли не совпадают',
            generic: 'Что-то пошло не так',
        },
    },
    en: {
        title: 'Password reset',
        subtitle: 'Enter your email, we will send you a code',
        email: 'Email',
        emailPlaceholder: 'Enter your email',
        code: 'Code from email',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        sendCode: 'Send code',
        sending: 'Sending…',
        verify: 'Verify code',
        checking: 'Checking…',
        resend: 'Resend code',
        submit: 'Change password',
        saving: 'Saving…',
        backToLogin: '← Back to login',
        placeholders: {
            new: 'At least 8 characters',
            confirm: 'Repeat new password',
        },
        errors: {
            mismatch: 'Passwords do not match',
            generic: 'Something went wrong',
        },
    },
    zh: {
        title: '重置密码',
        subtitle: '请输入邮箱，我们将向您发送验证码',
        email: '电子邮箱',
        emailPlaceholder: '请输入邮箱',
        code: '邮箱验证码',
        newPassword: '新密码',
        confirmPassword: '确认新密码',
        sendCode: '发送验证码',
        sending: '发送中…',
        verify: '验证验证码',
        checking: '验证中…',
        resend: '重新发送验证码',
        submit: '修改密码',
        saving: '保存中…',
        backToLogin: '← 返回登录',
        placeholders: {
            new: '至少 8 个字符',
            confirm: '请再次输入新密码',
        },
        errors: {
            mismatch: '密码不匹配',
            generic: '出现错误',
        },
    },
};